### ISSUE TITLE
MagicalPsi crashes the game

### ISSUE THREAD

**Issue by CommanderTvis** [wiiv/MagicalPsi#14]
Game crashes, when I try to wear Psi armor.

**Comment by CommanderTvis** [comment]
https://gist.github.com/CommanderTvis/1a1b298c43e6d286327acc6d66911ae2
This is the crash-report.

**Comment by Hubry** [comment]
Duplicate of #10 and #11, fixed in #12 but Wiiv still hasn't released a build despite he'll do it two weeks ago.
