### ISSUE TITLE
Crash at startup after Psi update r1.1-71

### ISSUE THREAD

**Issue by ate0ate** [wiiv/MagicalPsi#15]
I have been using Psi r1.1-70 alongside Magical Psi for a while now without issue but after updating to the new Psi release today(71) I now get this crash at startup...
https://pastebin.com/uhLJbdnJ
This is using forge 14.23.5.2815 as well.

**Comment by CommanderTvis** [comment]
Actual for me too

**Comment by Hubry** [comment]
Duplicate of #10, #11, #14, fixed in #12, spam Wiiv on twitter or discord or something because he was supposed to release an update two weeks ago.

**Comment by Hubry** [comment]
Use Psi 70 for now, it's broken on their side.

**Comment by ate0ate** [comment]
Not sure if this is helpful but I was playing around and compiled both Magical Psi and Psi and it seems compat is still broken. I was just curious if things would work since one of the recent commits to Psi is labeled "Fix some more magipsi incompat." It does still crash now but from NoSuchFieldError: psimetalShovel. Here's the log if needed... https://pastebin.com/FdatpFpp
Otherwise if this is completely useless info feel free to ignore me lol.

**Comment by ate0ate** [comment]
All is working well with the new update. Thanks!
