### ISSUE TITLE
flickering on the color changing bit on staves.

### ISSUE THREAD

**Issue by TechieJunk** [wiiv/MagicalPsi#2]
I have no idea if it's only flickering for myself.. I figured I should post here about it.
![javaw_2017-11-12_13-43-16](https://user-images.githubusercontent.com/7820646/32702114-b3871b08-c7af-11e7-90e3-51df225d9af1.png)
![javaw_2017-11-12_13-46-14](https://user-images.githubusercontent.com/7820646/32702124-ee0a2568-c7af-11e7-8e18-d59818fda0b6.png)

**Comment by Caopr** [comment]
Same issue with me

**Comment by TechieJunk** [comment]
I should note I tested this with just Psi and Magical Psi alone, no other mods.

**Comment by wiiv** [comment]
I know what is happening, fix incoming.

**Comment by EdC94** [comment]
![psi flickering](https://user-images.githubusercontent.com/13649970/33840612-b3744b34-de95-11e7-829b-606f883a4ab2.png)

Just to note: i still get the issue with the latest version of magical psi
MagicalPsi-1.3
forge 14.23.1.2560
