### ISSUE TITLE
Missed name change in text

### ISSUE THREAD

**Issue by Zsashas** [wiiv/MagicalPsi#4]
Should say Rod Varnish, not Colorizer

![2017-11-30_19 49 29](https://user-images.githubusercontent.com/6917535/33467210-ae3b1f76-d607-11e7-8b5c-7bb93a07bf43.png)

EDIT: Also, this should say to the RIGHT of the Rod, not Left.

![2017-11-30_20 12 14](https://user-images.githubusercontent.com/6917535/33467648-d7a81776-d60a-11e7-81ca-2b6678a413c0.png)

**Comment by wiiv** [comment]
Thank you for pointing those out!
