### ISSUE TITLE
Spell Inscriber floating page rendering is inconsistent

### ISSUE THREAD

**Issue by Zsashas** [wiiv/MagicalPsi#6]
At certain angles it appears blank, and renders block selection lines.

Also, could there be an option to make it more upright, like the programmer's floating display?

![2017-12-07_23 11 07](https://user-images.githubusercontent.com/6917535/33755092-1e07d302-dba4-11e7-90a5-b7b771b2e676.png)
![2017-12-07_23 11 12](https://user-images.githubusercontent.com/6917535/33755093-1e39dd70-dba4-11e7-875e-c02de411a929.png)
![2017-12-07_23 11 15](https://user-images.githubusercontent.com/6917535/33755094-1e4e8784-dba4-11e7-8e01-9d7d96392a64.png)

**Comment by wiiv** [comment]
I cannot reproduce this.
