### ISSUE TITLE
Something is very wrong with my Focusing Plate Helmet

### ISSUE THREAD

**Issue by Zsashas** [wiiv/MagicalPsi#7]
No idea what is happening, it was like this from the start.

![2017-12-09_01 00 32](https://user-images.githubusercontent.com/6917535/33794227-86983ffa-dc7c-11e7-80f4-7317ac08889a.png)
![2017-12-09_01 00 40](https://user-images.githubusercontent.com/6917535/33794228-86aeb546-dc7c-11e7-873b-5f288b4d3dc5.png)
![2017-12-09_01 00 44](https://user-images.githubusercontent.com/6917535/33794229-86c444c4-dc7c-11e7-96c1-9de3cbbd0fe0.png)

**Comment by Zsashas** [comment]
Followup: Chestplate is almost completely gone, and leggings just look like a belt.

**Comment by wiiv** [comment]
I can't reproduce this.

**Comment by Colorfold** [comment]
@Zsashas 
By chance, were you using Mo' Bends?
Because that's how my armor looks when I use Mo' Bends with Magical Psi.
